name: publish

on:
  push:
    branches:
      - main

jobs:

  prebuild:
    name: test, lint, type check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up environment
        run: >-
          pip install .[dev]
      - name: Test with pytest
        run: >-
          pytest -W error
      - name: Lint with ruff
        run: >-
          ruff check aqua_blue/
      - name: Type check with mypy
        run: >-
          mypy aqua_blue/

  quickstart:
    name: run quickstart
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12" ]
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up non-developer environment
        run: >-
          pip install .
      - name: Extract quickstart from README.md
        run: >-
          awk '/```py/,/```/' README.md | sed '1d;$d' > _quickstart.py
      - name: Run quickstart script
        run: >-
          python _quickstart.py

  build:
    needs:
      - prebuild
      - quickstart
    name: build distribution
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install pypa/build
        run: >-
          python -m pip install build --user
      - name: Build a binary wheel and a source tarball
        run: python -m build
      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  create-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: False
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: >-
          pip install .[dev]
      - name: Build pdoc documentation
        run: >-
          pdoc --html aqua_blue/ -o _build/
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pdoc-docs
          path: _build/

  deploy-docs:
    needs:
      - create-docs
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Download docs artifact
        uses: actions/download-artifact@v4
        with:
          name: pdoc-docs
          path: _build/

      # deploy here
      - name: Deploy documentation
        run: >-
          :

  pypi-publish:
    needs:
      - build
      - create-docs
    name: upload release to PyPI
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/aqua-blue
    permissions:
      id-token: write
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc

  notify-discord:
    needs: pypi-publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Send webhook payload to Discord
        run: |
          curl -H "Content-Type: application/json" \
               -X POST "${{ secrets.DISCORD_WEBHOOK_URL }}" \
               -d '{
                     "embeds": [
                       {
                         "title": "ðŸš€ New push to main branch of aqua-blue! ðŸŒŠ",
                         "description": "Repository: '${{ github.repository }}' at commit: '${{ github.sha }}'",
                         "color": 3447003,
                         "url": "https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
                       }
                     ]
                   }'
