name: publish

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:

  prebuild:
    name: test, lint, type check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    permissions:
      contents: read
    
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up dev environment
        run: >-
          pip install .[dev]
      - name: Set up example environment
        run: >-
          pip install .[examples]
      - name: Test with pytest
        run: >-
          coverage run -m pytest -W error
      - name: Create code coverage report
        run: >-
          coverage json
      - name: Print out code coverage percent
        run: >-
          echo "Coverage: $(jq '.totals.percent_covered' coverage.json)%"
      - name: Lint with ruff (dev)
        run: >-
          ruff check aqua_blue/
      - name: Type check with mypy (dev)
        run: >-
          mypy aqua_blue/
  
  quickstart:
    name: run quickstart
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up non-developer environment
        run: >-
          pip install .
      - name: Extract quickstart from README.md
        run: >-
          awk '/```py/,/```/' README.md | sed '1d;$d' > _quickstart.py
      - name: Run quickstart script
        run: >-
          python _quickstart.py

  examples:
    name: run examples
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up examples environment
        run: >-
          pip install .[examples]
      - name: Run example scripts
        run: >-
          for file in examples/*.py; do python "$file"; done

  build:
    if: github.event_name == 'release'
    needs:
      - prebuild
      - quickstart
      - examples
    name: build distribution
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install pypa/build
        run: >-
          python -m pip install build --user
      - name: Build a binary wheel and a source tarball
        run: python -m build
      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  create-docs:
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: False
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: >-
          pip install .[dev]
      - name: Build pdoc documentation
        run: >-
          pdoc -d google aqua_blue/ -o _build --math --logo "https://raw.githubusercontent.com/Chicago-Club-Management-Company/aqua-blue/refs/heads/main/assets/blue.jpg" --favicon "https://raw.githubusercontent.com/twitter/twemoji/master/assets/72x72/1f30a.png"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: github-pages
          path: _build/

  deploy-docs:
    if: github.event_name == 'release'
    needs:
      - create-docs
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download docs artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: _build/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  pypi-publish:
    if: github.event_name == 'release'
    needs:
      - build
      - deploy-docs
    name: upload release to PyPI
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/aqua-blue
    permissions:
      id-token: write
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc

  notify-discord:
    if: github.event_name == 'release'
    needs: deploy-docs
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Send webhook payload to Discord
        run: |
          curl -H "Content-Type: application/json" \
               -X POST "${{ secrets.DISCORD_WEBHOOK_URL }}" \
               -d '{
                     "embeds": [
                       {
                         "title": "ðŸš€ New push to main branch of aqua-blue! ðŸŒŠ",
                         "description": "Repository: '${{ github.repository }}' at commit: '${{ github.sha }}'",
                         "color": 3447003,
                         "url": "https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
                       }
                     ]
                   }'